"""empty message

Revision ID: 00ae1fa313e8
Revises: 6c49a39798c2
Create Date: 2023-12-09 16:58:17.554877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ae1fa313e8'
down_revision = '6c49a39798c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_9', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key('user_images_ibfk_9', 'sexuals', ['sexual'], ['id'])

    # ### end Alembic commands ###
