"""empty message

Revision ID: 082bcbc1025c
Revises: 38802532e362
Create Date: 2023-12-06 10:43:24.928289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '082bcbc1025c'
down_revision = '38802532e362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorynames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.drop_table('calender')
    op.drop_table('event')
    op.drop_table('categoryname')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('hash_token')
        batch_op.drop_index('name')

    op.drop_table('user')
    op.drop_table('shared_user_calender')
    op.drop_table('extypes')
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categorynames', ['category'], ['id'])
        batch_op.create_foreign_key(None, 'sexuals', ['sex'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('extypes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exname', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('shared_user_calender',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calender_id'], ['calender.uid'], name='shared_user_calender_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], name='shared_user_calender_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'calender_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('hash_token', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('hash_token', ['hash_token'], unique=False)

    op.create_table('categoryname',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryname', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ical_uid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('is_show', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_all_day', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('rrule', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['calender_id'], ['calender.uid'], name='event_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calender',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('ical_url', mysql.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], name='calender_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('categorynames')
    # ### end Alembic commands ###
