"""empty message

Revision ID: 0f118dd9e9b5
Revises: cf860e7bcf4c
Create Date: 2023-11-30 15:28:09.975647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f118dd9e9b5'
down_revision = 'cf860e7bcf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.Integer(), nullable=True))
        batch_op.drop_column('is_detected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_detected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('sold')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
