"""empty message

Revision ID: 14014069a26a
Revises: 4bf038c5936c
Create Date: 2024-02-01 16:12:41.885610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14014069a26a'
down_revision = '4bf038c5936c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['user_images.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_12', type_='foreignkey')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_images_ibfk_12', 'users', ['buyer_id'], ['id'])

    op.drop_table('sellinfos')
    # ### end Alembic commands ###
