"""empty message

Revision ID: 21039d53045b
Revises: bb65f9eb6cf7
Create Date: 2023-11-30 18:47:54.470770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21039d53045b'
down_revision = 'bb65f9eb6cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('user_images_ibfk_3', type_='foreignkey')
        batch_op.drop_column('colors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_images_ibfk_3', 'sexuals', ['sex'], ['id'])
        batch_op.create_foreign_key('user_images_ibfk_4', 'colors', ['color'], ['id'])

    # ### end Alembic commands ###
