"""empty message

Revision ID: 21687226a1ab
Revises: 00ae1fa313e8
Create Date: 2023-12-09 17:03:42.321515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21687226a1ab'
down_revision = '00ae1fa313e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('user_images_ibfk_6', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key('user_images_ibfk_6', 'sizes', ['size'], ['id'])
        batch_op.create_foreign_key('user_images_ibfk_3', 'conditions', ['condition'], ['id'])

    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
