"""empty message

Revision ID: 28246e41c8f7
Revises: 0e802daa6bc2
Create Date: 2023-12-01 16:48:36.520944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28246e41c8f7'
down_revision = '0e802daa6bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key('user_images_ibfk_2', 'colors', ['color'], ['id'])

    # ### end Alembic commands ###
