"""empty message

Revision ID: 32e5aec4316e
Revises: fb4d1d3f9c23
Create Date: 2023-12-09 15:49:20.302179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32e5aec4316e'
down_revision = 'fb4d1d3f9c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint('user_images_ibfk_4', type_='foreignkey')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_images_ibfk_4', 'colors', ['color'], ['id'])

    # ### end Alembic commands ###
