"""empty message

Revision ID: 49d9d6b403c2
Revises: 9a517e3e50c5
Create Date: 2023-11-08 08:47:28.993658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d9d6b403c2'
down_revision = '9a517e3e50c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('condition')
        batch_op.drop_column('size')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
