"""empty message

Revision ID: 4fcbf9918a0f
Revises: 26944899d58a
Create Date: 2023-11-30 18:25:10.274724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fcbf9918a0f'
down_revision = '26944899d58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorynames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.drop_table('categoryname')
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_images_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'colors', ['colors'], ['id'])
        batch_op.create_foreign_key(None, 'categorynames', ['category'], ['id'])
        batch_op.create_foreign_key(None, 'conditions', ['condition'], ['id'])
        batch_op.create_foreign_key(None, 'sizes', ['size'], ['id'])
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_images_ibfk_2', 'colors', ['color'], ['id'])
        batch_op.drop_column('colors')

    op.create_table('categoryname',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryname', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('categorynames')
    # ### end Alembic commands ###
