"""empty message

Revision ID: 6749326be379
Revises: 18a0a39db30a
Create Date: 2023-11-30 17:30:27.800074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6749326be379'
down_revision = '18a0a39db30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categorynames', ['category'], ['categoryname'])
        batch_op.create_foreign_key(None, 'conditions', ['condition'], ['condition'])
        batch_op.create_foreign_key(None, 'sizes', ['size'], ['size'])
        batch_op.create_foreign_key(None, 'colors', ['color'], ['color'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
