"""empty message

Revision ID: 6c69c06e7bde
Revises: d2bbb0359552
Create Date: 2024-02-19 16:23:04.534400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c69c06e7bde'
down_revision = 'd2bbb0359552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('follows_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('follows_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.drop_column('follow')
        batch_op.drop_column('follower')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('follow', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follows_ibfk_1', 'users', ['follow'], ['id'])
        batch_op.create_foreign_key('follows_ibfk_2', 'users', ['follower'], ['id'])
        batch_op.drop_column('follower_id')
        batch_op.drop_column('follow_id')

    # ### end Alembic commands ###
