"""empty message

Revision ID: 86b8085bf28d
Revises: 082bcbc1025c
Create Date: 2023-12-06 10:59:25.153614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b8085bf28d'
down_revision = '082bcbc1025c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extypes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('hash_token')
        batch_op.drop_index('name')

    op.drop_table('user')
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categorynames', ['category'], ['id'])
        batch_op.create_foreign_key(None, 'sexuals', ['sex'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('user',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('hash_token', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('hash_token', ['hash_token'], unique=False)

    op.create_table('extypes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exname', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
