"""empty message

Revision ID: 8a125ac19db0
Revises: 0f118dd9e9b5
Create Date: 2023-11-30 16:51:07.656608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a125ac19db0'
down_revision = '0f118dd9e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorynames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('extypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('productcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productcategories')
    op.drop_table('extypes')
    op.drop_table('categorynames')
    # ### end Alembic commands ###
