"""empty message

Revision ID: 8d74be3d0ff7
Revises: 49d9d6b403c2
Create Date: 2023-11-09 16:48:59.790215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d74be3d0ff7'
down_revision = '49d9d6b403c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follow'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fullname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('furigana', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('noticeid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('points')
        batch_op.drop_column('noticeid')
        batch_op.drop_column('furigana')
        batch_op.drop_column('fullname')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('icon_path')
        batch_op.drop_column('profile')

    op.drop_table('follows')
    # ### end Alembic commands ###
