"""empty message

Revision ID: a1d27a3321b7
Revises: 6c69c06e7bde
Create Date: 2024-02-19 16:25:34.577156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d27a3321b7'
down_revision = '6c69c06e7bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellinfos', schema=None) as batch_op:
        batch_op.drop_constraint('sellinfos_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellinfos', schema=None) as batch_op:
        batch_op.create_foreign_key('sellinfos_ibfk_1', 'users', ['buyer_id'], ['id'])

    # ### end Alembic commands ###
