"""empty message

Revision ID: b6c24d62aff6
Revises: ef84dfba4c14
Create Date: 2023-11-30 18:05:14.108598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6c24d62aff6'
down_revision = 'ef84dfba4c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sizes', ['size'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
