"""empty message

Revision ID: b75a8facec99
Revises: 32e5aec4316e
Create Date: 2023-12-09 15:50:23.595044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75a8facec99'
down_revision = '32e5aec4316e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'colors', ['color'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
