"""empty message

Revision ID: cf860e7bcf4c
Revises: 8d74be3d0ff7
Create Date: 2023-11-09 17:25:49.536121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf860e7bcf4c'
down_revision = '8d74be3d0ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
